repos:

  # precommit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml

  # black, isort, ruff, pytest
  - repo: local
    hooks:
      - id: black
        name: black
        entry: bash -c "cd flask-app && poetry run black ."
        language: system
        types: [python]
      - id: isort
        name: isort
        entry: bash -c "cd flask-app && poetry run isort ."
        language: system
        types: [python]
      - id: ruff
        name: ruff
        entry: bash -c "cd flask-app && poetry run ruff ."
        language: system
        types: [python]
      - id: run_tests
        name: run_tests
        entry: bash -c "cd flask-app && poetry run pytest"
        language: system
        types: [python]
