name: docker-ci

on:
  workflow_run:
    workflows: [backend-ci]
    types:
      - completed
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  flask-app-ci:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo & set up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3

      #----------------------------------------------
      #        Set up docker cache
      #----------------------------------------------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker Images
        uses: ScribeMD/docker-cache@0.3.7
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('docker-compose.yaml') }}

      #----------------------------------------------
      #        Run tests with docker build
      #----------------------------------------------
      - name: Run tests
        run: |
          docker-compose -f docker-compose.yml build

      - name: Docker clean up
        run: |
          docker-compose -f docker-compose.yml down
